# .github/workflows/ci-cd.yml
name: Java CI/CD with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8.0_311
          distribution: 'ubuntu'

      - name: Build with Maven
        run: mvn -B clean install

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8.0_311
          distribution: 'ubuntu'

      - name: Deploy to Server
        run: |
          echo "Deploying login page to production server..."
